# name: Development Workflow

# on:
#   push:
#     branches:
#       - test-dev

# jobs:
#   deploy-production:
#     name: Deploy project to production server
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/test-dev'
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: Deployment
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SSH_IP }}
#         key: ${{ secrets.SSH_PRIVATE_KEY_DO }}
#         port: ${{ secrets.SSH_PORT }}
#         username: ${{ secrets.SSH_USERNAME }}
#         script: |
#           cd ~/apps/betlify
#           git pull
#           npm install
#           pm2 pm2-runtime reload ecosystem.config.js --env staging